controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

well_known_ignore:
    path: /.well-known/{any}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: false
    requirements:
        any: .*